//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiffzack.Devices.CardTerminals.Protocols.ZVT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangDe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangDe() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wiffzack.Devices.CardTerminals.Protocols.ZVT.LangDe", typeof(LangDe).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion nicht durchführbar.
        /// </summary>
        internal static string IntermediateStatusApduResponse_ActionNotPossible {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_ActionNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatischer Kassenschnitt wird durchgeführt.
        /// </summary>
        internal static string IntermediateStatusApduResponse_AutomaticEndOfDay {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_AutomaticEndOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte abgelaufen.
        /// </summary>
        internal static string IntermediateStatusApduResponse_CardExpired {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_CardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte ungültig.
        /// </summary>
        internal static string IntermediateStatusApduResponse_CardInvalid {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_CardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte unzulässig.
        /// </summary>
        internal static string IntermediateStatusApduResponse_CardNotPermitted {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_CardNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte nicht lesbar.
        /// </summary>
        internal static string IntermediateStatusApduResponse_CardNotReadable {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_CardNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannte Karte.
        /// </summary>
        internal static string IntermediateStatusApduResponse_CardUnknown {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_CardUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte einführen.
        /// </summary>
        internal static string IntermediateStatusApduResponse_InsertCard {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_InsertCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display von PIN-Pad beachten.
        /// </summary>
        internal static string IntermediateStatusApduResponse_NoteDisplayPinPad {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_NoteDisplayPinPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display von PIN-Pad beachten.
        /// </summary>
        internal static string IntermediateStatusApduResponse_NoteDisplayPinPad2 {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_NoteDisplayPinPad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgang abgebrochen.
        /// </summary>
        internal static string IntermediateStatusApduResponse_ProcessCancelled {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_ProcessCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeite....
        /// </summary>
        internal static string IntermediateStatusApduResponse_Processing {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal sendet Nachbuchungen.
        /// </summary>
        internal static string IntermediateStatusApduResponse_PTSendingPostBookings {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_PTSendingPostBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal führt Auto-Stornierung durch.
        /// </summary>
        internal static string IntermediateStatusApduResponse_PTSendsAutoReversal {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_PTSendsAutoReversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warte auf Bestätigung des Betrages....
        /// </summary>
        internal static string IntermediateStatusApduResponse_PTWaitingForAmountConfirmation {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_PTWaitingForAmountConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte entfernen.
        /// </summary>
        internal static string IntermediateStatusApduResponse_RemoveCard {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_RemoveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal wartet auf FEP Antwort.
        /// </summary>
        internal static string IntermediateStatusApduResponse_WaitingForFEPResponse {
            get {
                return ResourceManager.GetString("IntermediateStatusApduResponse_WaitingForFEPResponse", resourceCulture);
            }
        }
    }
}
